
export const SCREEN = {
  SCREEN_MODE: 'SCREEN_MODE',
};

export const WEATHER = {
  SET_CURRENT_LOCATION_KEY: 'SET_CURRENT_LOCATION_KEY',
  SET_CURRENT_LOCATION_NAME: 'SET_CURRENT_LOCATION_NAME',
  SET_CURRENT_LOCATION_WEATHER: 'SET_CURRENT_LOCATION_WEATHER',
  SET_UNITS: 'SET_UNITS',
};

export const THEME = {
  SET_DARK_MODE: 'SET_DARK_MODE',
};